# 2023-05-21 22:10
#
#
name: 0-act - sciter - Win-Win32-Arm - cstm

on:
  workflow_call:
  workflow_dispatch:
#  schedule:
#    # schedule build every night
#    - cron: "0 0 * * *"

env:
  TAG_VERSION: "rdsk-v1.2.0"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"
  TAG_NAME: "Win-Win32-Arm-cstm"
  # To make a custom build with your own servers set the below secret values
  RS_PUB_KEY: '${{ secrets.RS_PUB_KEY }}'
  RENDEZVOUS_SERVER: '${{ secrets.RENDEZVOUS_SERVER }}'
  RDSK_PCH_SH_PRE: '${{ secrets.RDSK_PCH_SH_PRE }}'
  RDSK_PCH_SH: '${{ secrets.RDSK_PCH_SH }}'
  RDSK_PCH_HL: '${{ secrets.RDSK_PCH_HL }}'
  RDSK_PCH_SH2: '${{ secrets.RDSK_PCH_SH2 }}'
  RDSK_PCH_SH_CLN: '${{ secrets.RDSK_PCH_SH_CLN }}'
  DEBUG_LS: "yes"
  LLVM_VERSION: "15.0.6"
  # vcpkg version: 2023.04.15
  # for multiarch gcc compatibility
  VCPKG_COMMIT_ID: "501db0f17ef6df184fcdbfbe0f87cde2313b6ab1"
  VERSION: "1.2.0"
  GUI: "sciter"

jobs:
  build-for-windows-sciter:
    uses: ./.github/workflows/act-sciter-Win-cstm.yml
    secrets: inherit

  build-for-windows-sciter-32bit:
    uses: ./.github/workflows/act-sciter-Win-32bit-cstm.yml
    secrets: inherit

  build-for-arm-sciter:
    uses: ./.github/workflows/act-sciter-Arm-cstm.yml
    secrets: inherit
